disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - redundant_discardable_let
  - cyclomatic_complexity
  - function_body_length
  # - trailing_whitespace
  - vertical_whitespace
  - file_length
  # - colon
  - type_body_length
  - comment_spacing
  - comma
  - todo
  - trailing_newline
  # - control_statement
  # - opening_brace
  - switch_case_alignment
  # - unused_closure_parameter
  - force_cast
  # - force_try
  # - shorthand_operator
  # - identifier_name
  - syntactic_sugar
  # - empty_parentheses_with_trailing_closure
  # - legacy_constructor
  # - multiple_closures_with_trailing_closure
  - unused_enumerated
  # - redundant_void_return
  # - for_where
  - vertical_parameter_alignment
  - type_name
